# -*- coding: utf-8 -*-
"""MiniCurso_py_analise_de_dados_pokemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foyGVxfIu2vJQxN9K5jtoMj8_RUwjozm
"""

import pandas as pd

df = pd.read_csv('Pokemon.csv')
print(df)

df.head()

df.info()

df.describe()

print(df['Attack'].mean())
print(df['Defense'].mean())

filto = filtro.groupby(['Type 1']).count()
print(filto)

df = pd.read_csv('Pokemon.csv')

filtro = df[df['Generation'] == 1]
print(filtro)

filtro

agrupado = filtro.groupby(['Type 1'])['Generation'].sum().reset_index()

print(agrupado)

import matplotlib.pyplot as plt

plt.pie(agrupado['Generation'], labels=agrupado['Type 1'], autopct='%1.1f%%')

plt.title('Tipos de Pokemons')
plt.show()