# Generated by Django 5.1.4 on 2024-12-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
